/**
 * HTTP client for the LLM Wiki desktop daemon.
 *
 * The daemon runs at http://127.0.0.1:19827 and exposes `/api/*` routes that
 * are gated behind a bearer token. The token is generated by the desktop app
 * on first launch and persisted at:
 *   - macOS:  ~/Library/Application Support/llm-wiki/api-token
 *   - Linux:  $XDG_CONFIG_HOME/llm-wiki/api-token  (or ~/.config/llm-wiki/api-token)
 *   - Windows: %APPDATA%/llm-wiki/api-token
 *
 * The MCP server reads the token from disk (or the LLM_WIKI_API_TOKEN env var)
 * so users don't have to copy/paste it.
 */

import { fetch } from "undici"
import { readFileSync } from "node:fs"
import { homedir, platform } from "node:os"
import { join } from "node:path"

const DEFAULT_BASE = "http://127.0.0.1:19827"
const TOKEN_ENV = "LLM_WIKI_API_TOKEN"
const BASE_ENV = "LLM_WIKI_API_URL"

export interface ClientOptions {
  baseUrl?: string
  token?: string
  fetchTimeoutMs?: number
}

export class DaemonUnreachableError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "DaemonUnreachableError"
  }
}

export class ApiError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly body: unknown,
  ) {
    super(message)
    this.name = "ApiError"
  }
}

/** Resolve the on-disk path that the desktop app writes the API token to. */
export function defaultTokenPath(): string {
  const env = process.env
  switch (platform()) {
    case "win32": {
      const appdata = env.APPDATA ?? join(homedir(), "AppData", "Roaming")
      return join(appdata, "llm-wiki", "api-token")
    }
    case "darwin":
      return join(homedir(), "Library", "Application Support", "llm-wiki", "api-token")
    default: {
      const xdg = env.XDG_CONFIG_HOME ?? join(homedir(), ".config")
      return join(xdg, "llm-wiki", "api-token")
    }
  }
}

/** Best-effort token resolution: env var first, then on-disk token file. */
export function resolveToken(): string {
  const fromEnv = process.env[TOKEN_ENV]
  if (fromEnv && fromEnv.length > 0) return fromEnv.trim()
  try {
    return readFileSync(defaultTokenPath(), "utf8").trim()
  } catch (err) {
    throw new DaemonUnreachableError(
      `Could not read API token at ${defaultTokenPath()}. Make sure the LLM Wiki desktop app has been launched at least once, or set ${TOKEN_ENV}. (${err instanceof Error ? err.message : String(err)})`,
    )
  }
}

export class WikiDaemonClient {
  private readonly baseUrl: string
  private readonly fetchTimeoutMs: number
  private readonly tokenOverride?: string
  private cachedToken: string | null = null

  // Token resolution is intentionally deferred to the first request so that
  // the MCP server can boot (and the inspector's stdio handshake can complete)
  // even when the desktop app hasn't been launched yet — the token file at
  // `%APPDATA%/llm-wiki/api-token` may not exist, or the spawning host may not
  // forward `APPDATA`. A failure to read it is surfaced per-tool-call as a
  // `DaemonUnreachableError` instead of crashing the process at startup.
  constructor(options: ClientOptions = {}) {
    this.baseUrl =
      options.baseUrl ?? process.env[BASE_ENV] ?? DEFAULT_BASE
    this.tokenOverride = options.token
    this.fetchTimeoutMs = options.fetchTimeoutMs ?? 60_000
  }

  /** Resolve and cache the bearer token. Throws if it can't be read. */
  private getToken(): string {
    if (this.cachedToken) return this.cachedToken
    if (this.tokenOverride) {
      this.cachedToken = this.tokenOverride
      return this.cachedToken
    }
    this.cachedToken = resolveToken()
    return this.cachedToken
  }

  /** Issue a JSON request and parse the response. Throws `ApiError` on non-2xx. */
  async request<T = unknown>(
    method: "GET" | "POST" | "DELETE",
    path: string,
    options: { body?: unknown; query?: Record<string, string | number | undefined> } = {},
  ): Promise<T> {
    const url = new URL(path, this.baseUrl)
    if (options.query) {
      for (const [k, v] of Object.entries(options.query)) {
        if (v !== undefined && v !== null && v !== "") {
          url.searchParams.set(k, String(v))
        }
      }
    }

    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), this.fetchTimeoutMs)

    // GET (and other body-less verbs) MUST NOT carry a request body — undici's
    // fetch raises if you try, and the daemon doesn't expect one anyway. We
    // surface body-only data as query params instead at the call site.
    const sendBody = method !== "GET" && options.body !== undefined

    let token: string
    try {
      token = this.getToken()
    } catch (err) {
      clearTimeout(timer)
      throw err
    }

    let response
    try {
      response = await fetch(url, {
        method,
        headers: {
          "Authorization": `Bearer ${token}`,
          ...(sendBody ? { "Content-Type": "application/json" } : {}),
        },
        body: sendBody ? JSON.stringify(options.body) : undefined,
        signal: controller.signal,
      })
    } catch (err) {
      throw new DaemonUnreachableError(
        `Failed to reach LLM Wiki daemon at ${this.baseUrl}. Is the desktop app running? (${err instanceof Error ? err.message : String(err)})`,
      )
    } finally {
      clearTimeout(timer)
    }

    let parsed: unknown = null
    const text = await response.text()
    if (text.length > 0) {
      try {
        parsed = JSON.parse(text)
      } catch {
        parsed = text
      }
    }

    if (!response.ok) {
      const message = extractErrorMessage(parsed) ?? `HTTP ${response.status}`
      throw new ApiError(message, response.status, parsed)
    }

    return parsed as T
  }

  /**
   * Subscribe to the SSE progress stream for `jobId`. The async iterator yields
   * progress events parsed from `data:` lines. Closes when the daemon emits an
   * `event: done` frame or the iterator is broken out of.
   */
  async *streamJob(jobId: string, options: { signal?: AbortSignal } = {}): AsyncIterable<JobEvent> {
    const url = new URL(`/api/jobs/${encodeURIComponent(jobId)}/stream`, this.baseUrl)
    const controller = new AbortController()
    if (options.signal) {
      options.signal.addEventListener("abort", () => controller.abort())
    }

    const token = this.getToken()
    let response
    try {
      response = await fetch(url, {
        method: "GET",
        headers: {
          "Authorization": `Bearer ${token}`,
          "Accept": "text/event-stream",
        },
        signal: controller.signal,
      })
    } catch (err) {
      throw new DaemonUnreachableError(
        `SSE connection failed: ${err instanceof Error ? err.message : String(err)}`,
      )
    }

    if (!response.ok || !response.body) {
      throw new ApiError(`SSE handshake failed: HTTP ${response.status}`, response.status, null)
    }

    const decoder = new TextDecoder("utf-8")
    let buf = ""

    try {
      // undici v8 returns a WHATWG ReadableStream; getReader() is the most
      // portable way to consume it (`for await` requires a Symbol.asyncIterator
      // implementation that some Node versions / polyfills miss).
      const reader = (response.body as ReadableStream<Uint8Array>).getReader()
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        if (!value) continue
        buf += decoder.decode(value, { stream: true })
        // Frames are separated by a blank line, which is `\n\n` for compliant
        // servers and `\r\n\r\n` for some HTTP stacks. Handle both.
        let idx = nextFrameBoundary(buf)
        while (idx !== -1) {
          const frame = buf.slice(0, idx.start)
          buf = buf.slice(idx.start + idx.length)
          const event = parseSseFrame(frame)
          if (event) {
            yield event
            if (event.kind === "done") {
              return
            }
          }
          idx = nextFrameBoundary(buf)
        }
      }
    } finally {
      controller.abort()
    }
  }
}

export interface JobEvent {
  kind: "progress" | "done" | "error" | "running" | "comment"
  data: {
    jobId?: string
    status?: string
    detail?: string
    progress?: number
    data?: unknown
    error?: string
    done?: boolean
  }
}

function nextFrameBoundary(buf: string): { start: number; length: number } | -1 {
  const lf = buf.indexOf("\n\n")
  const crlf = buf.indexOf("\r\n\r\n")
  if (lf === -1 && crlf === -1) return -1
  if (lf === -1) return { start: crlf, length: 4 }
  if (crlf === -1) return { start: lf, length: 2 }
  return lf < crlf ? { start: lf, length: 2 } : { start: crlf, length: 4 }
}

function parseSseFrame(frame: string): JobEvent | null {
  let kind = "progress"
  let dataLine = ""
  for (const line of frame.split(/\r?\n/)) {
    if (line.startsWith(":")) {
      // SSE comment / keepalive — ignore.
      continue
    }
    if (line.startsWith("event:")) {
      kind = line.slice(6).trim()
    } else if (line.startsWith("data:")) {
      dataLine += line.slice(5).trim()
    }
  }
  if (!dataLine) return null
  try {
    return { kind: kind as JobEvent["kind"], data: JSON.parse(dataLine) }
  } catch {
    return { kind: kind as JobEvent["kind"], data: { detail: dataLine } }
  }
}

function extractErrorMessage(body: unknown): string | null {
  if (body && typeof body === "object" && "error" in body) {
    const err = (body as { error: unknown }).error
    if (typeof err === "string") return err
  }
  return null
}
